# Generated by Django 3.2.4 on 2021-06-27 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('teacher_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.IntegerField()),
                ('address', models.TextField()),
                ('student_code', models.CharField(max_length=200)),
                ('class_model', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='students.classmodel')),
            ],
        ),
    ]
