# Generated by Django 3.2.4 on 2021-07-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20210719_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='Tên sinh viên, ví dụ:  Nguyễn Văn A', max_length=200),
        ),
    ]
