# Generated by Django 3.2.4 on 2021-08-08 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20210808_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=255, null=True, unique=True)),
                ('dob', models.DateField(null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='subjectregistration',
            name='reg_at',
            field=models.DateField(null=True, verbose_name='Ngày đăng ký'),
        ),
        migrations.AlterField(
            model_name='subjectregistration',
            name='score',
            field=models.FloatField(default=0, verbose_name='Điểm trung bình'),
        ),
        migrations.AlterField(
            model_name='subjectregistration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Sinh viên'),
        ),
        migrations.AlterField(
            model_name='subjectregistration',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.subject', verbose_name='Môn học'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.profile'),
        ),
    ]
