# Generated by Django 3.2.4 on 2021-10-10 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20210919_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('change_task_status', 'Can change the status of tasks'), ('close_task', 'Can remove a task by setting its status as closed')]},
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.order', verbose_name='Đơn hàng'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.product', verbose_name='Sản phẩm'),
        ),
    ]
