# Generated by Django 3.2.4 on 2021-10-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20211010_0731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': [('change_task_status', 'Can change the status of tasks'), ('close_task', 'Can remove a task by setting its status as closed'), ('grade_latest_exam_score', 'Cập nhật điểm đồ án tốt nghiệp')]},
        ),
    ]
